<?php

namespace AppBundle\Entity;

/**
 * AddMoneyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddMoneyRepository extends \Doctrine\ORM\EntityRepository
{
}
