<?php

namespace AppBundle\Entity;

/**
 * AddUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddUserRepository extends \Doctrine\ORM\EntityRepository
{
}
